services:
  spark-master:
    image: "apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu"
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./localvolumes/all_logs:/opt/spark/logs
      - ./localvolumes/all_conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf  
    command: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-master.sh --host spark-master && tail -f /dev/null"
    networks:
      - streaming-stack
  spark-worker:
    image: "apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu"
    container_name: spark-worker
    hostname: spark-worker
    volumes:    
      - ./localvolumes/all_logs:/opt/spark/logs
      - ./localvolumes/all_conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf      
    command: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 --host spark-worker  && tail -f /dev/null"      
    networks:
      - streaming-stack
  spark-connect:
    image: "apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu"
    container_name: spark-connect
    hostname: spark-connect
    ports:
      - "4040:4040"
      - "15002:15002"
    depends_on:
      - spark-master
    volumes:
      - ./localvolumes/jars/spark-connect_2.13-4.0.1.jar:/opt/spark/jars/spark-connect_2.13-4.0.1.jar
      - ./localvolumes/sc-work-dir:/opt/spark/work-dir:rw
      - ./localvolumes/ivycache:/opt/spark/ivycache:rw
      - ./localvolumes/all_logs:/opt/spark/logs
      - ./localvolumes/all_conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf      
    command: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-connect-server.sh --jars /opt/spark/jars/spark-connect_2.13-4.0.1.jar && tail -f /dev/null"
    networks:
    - streaming-stack
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "./localvolumes/kafkadata:/tmp/kafka-logs"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_LISTENERS=LISTENER_BOB://kafka:29092,LISTENER_FRED://kafka:9092,CONTROLLER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_BOB
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      #- KAFKA_LOG_DIRS=/tmp/kafka-logs
    networks:
      - streaming-stack
  kafka-ui:
    image: "provectuslabs/kafka-ui"
    ports:
      - "9080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=streaming-demo
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - streaming-stack

volumes:
  kafka_data:
  
networks:
  streaming-stack:
